_BASE_: MOX_SLOW_PROG_36x8_R50_stepwise.yaml

DATA:
  PATH_TO_DATA_DIR: obs://video-understanding-shanghai/penggao/data/Kinetics/
  PATH_PREFIX: obs://video-understanding-shanghai/poli/datasets/Kinetics/

LOGS:
  DIR: obs://video-understanding-shanghai/penggao/logs/progress-action/Kinetics/MOX2_SLOW_PROG_36x8_R50_stepwise

NUM_SHARDS: 2