_BASE_: SLOW_8x8_R50_stepwise.yaml

TRAIN:
  BATCH_SIZE: 256
  EVAL_PERIOD: 1

DATA:
  PATH_TO_DATA_DIR: obs://video-understanding-shanghai/penggao/data/Kinetics/
  PATH_PREFIX: obs://video-understanding-shanghai/poli/datasets/Kinetics/

SOLVER:
  BASE_LR: 0.8
  WARMUP_START_LR: 0.08

TEST:
  BATCH_SIZE: 64

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://video-understanding-shanghai/penggao/logs/progress-action/Kinetics/MOX_SLOW_8x8_R50_stepwise

NUM_SHARDS: 2