_BASE_: SLOWFAST_PROG_36x8_R101.yaml

DATA:
  PATH_TO_DATA_DIR: obs://video-understanding-shanghai/penggao/data/Kinetics/
  PATH_PREFIX: obs://video-understanding-shanghai/poli/datasets/Kinetics/

SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://video-understanding-shanghai/penggao/logs/progress-action/Kinetics/MOX2_SLOWFAST_PROG_36x8_R101

NUM_SHARDS: 4