_BASE_: SLOW_PROG_36x8_R101_50.yaml

DATA:
  PATH_TO_DATA_DIR: obs://video-understanding-shanghai/penggao/data/Kinetics/
  PATH_PREFIX: obs://video-understanding-shanghai/poli/datasets/Kinetics/

SOLVER:
  BASE_LR: 0.4
  WARMUP_START_LR: 0.04

LOGS:
  DIR: obs://video-understanding-shanghai/penggao/logs/progress-action/Kinetics/MOX2_SLOW_PROG_36x8_R101_50

NUM_SHARDS: 4