_BASE_: SLOW_8x8_R50.yaml

TRAIN:
  EVAL_PERIOD: 10

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Kinetics_400/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Kinetics/MOX_SLOW_8x8_R50