_BASE_: SLOWFAST_NLN_8x8_R101_50_50.yaml

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Kinetics_400/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

SOLVER:
  BASE_LR: 0.2
  WARMUP_START_LR: 0.02

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Kinetics/MOX_SLOWFAST_NLN_8x8_R101_50_50

NUM_SHARDS: 2
