_BASE_: SLOWFAST_8x8_R50.yaml

TRAIN:
  BATCH_SIZE: 128

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Kinetics_400/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

SOLVER:
  BASE_LR: 0.4
  WARMUP_START_LR: 0.04

DATA_LOADER:
  NUM_WORKERS: 7

TEST:
  BATCH_SIZE: 128

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Kinetics/MOX_SLOWFAST_8x8_R50

NUM_SHARDS: 2
