_BASE_: X3D_XL.yaml

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Kinetics_400/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

SOLVER:
  BASE_LR: 0.1
  WARMUP_START_LR: 0.02

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Kinetics/MOX_X3D_XL
  LOG_MODEL: True

NUM_SHARDS: 4