_BASE_: SLOW_8x8_R101_50.yaml

TRAIN:
  EVAL_PERIOD: 10
  BATCH_SIZE: 128

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Kinetics_400/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

TEST:
  BATCH_SIZE: 128

SOLVER:
  BASE_LR: 0.4
  WARMUP_START_LR: 0.04

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Kinetics/MOX_SLOW_8x8_R101_50

NUM_SHARDS: 2