_BASE_: SLOW_PROG_36x8_R50_train_together.yaml

TRAIN:
  BATCH_SIZE: 128

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Kinetics_400/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

SOLVER:
  BASE_LR: 0.4
  WARMUP_START_LR: 0.04

TEST:
  BATCH_SIZE: 32

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Kinetics/MOX_SLOW_PROG_36x8_R50_train_together

NUM_SHARDS: 2