_BASE_: R3D_8x8_400M.yaml

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: 8

SOLVER:
  MAX_EPOCH: 98
  WARMUP_EPOCHS: 17.0

TEST:
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Kinetics/R3D_PROG_36x8_400M