_BASE_: SLOW_8x8_R101_50.yaml

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: [8]
  STEPS: 5
  OVERLAP: [1]
  PG_EVAL: False
  TRAIN_TOGETHER: True

SOLVER:
  MAX_EPOCH: 98
  WARMUP_EPOCHS: 17.0
  WEIGHT_DECAY: 2e-4

TEST:
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Kinetics/SLOW_PROG_36x8_R101_50