_BASE_: SLOWFAST_8x8_R101.yaml

TRAIN:
  EVAL_PERIOD: 1

DATA:
  NUM_FRAMES: 144

PGT:
  ENABLE: True
  STEP_LEN: [8, 32]
  STEPS: 5
  OVERLAP: [1, 4]
  TRAIN_TOGETHER: True
  PG_EVAL: False
  TPOOL_SIZE: [4, 4]

SOLVER:
  MAX_EPOCH: 98
  WARMUP_EPOCHS: 17.0
  WEIGHT_DECAY: 2e-4

TEST:
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Kinetics/SLOWFAST_PROG_36x8_R50