TRAIN:
  DATASET: kinetics
  BATCH_SIZE: 128
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12

TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 3

DATA:
  NUM_FRAMES: 4
  SAMPLING_RATE: 12
  TRAIN_JITTER_SCALES: [182, 228]
  TRAIN_CROP_SIZE: 160
  TEST_CROP_SIZE: 182
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/pg/data/Kinetics_400/
  PATH_PREFIX: /home/pg/data/Kinetics_400/

RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.1
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 300
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 400
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

LOGS:
  DIR: logs/Kinetics/X3D_XS
  LOG_MODEL: True

NUM_GPUS: 8
RNG_SEED: 0
