_BASE_: I3D_8x8_R50_K400.yaml

TRAIN:
  CHECKPOINT_FILE_PATH: /home/pg/data/models/k400/I3D_NLN_8x8_R50.pkl

NONLOCAL:
  LOCATION: [[[]], [[1, 3]], [[1, 3, 5]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
  USE_BN: False

LOGS:
  DIR: logs/Charades/I3D_NLN_8x8_R50_K400