TRAIN:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: data/models/k400/i3d_baseline_32x4_I3D_pretrain_400k.pkl
  CHECKPOINT_TYPE: caffe2
  AUTO_RESUME: True

DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data/charades/
  PATH_PREFIX: data/charades/Charades_v1_rgb
  MULTI_LABEL: True
  ENSEMBLE_METHOD: max

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]

NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax

BN:
  USE_PRECISE_STATS: False
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
  NORM_TYPE: frozen_batchnorm

SOLVER:
  BASE_LR: 0.02
  LR_POLICY: steps_with_relative_lrs
  MAX_EPOCH: 48
  STEPS: [0, 40, 48]
  LRS: [1, 0.1, 0.01]
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1.25e-5
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 157
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.3
  HEAD_ACT: sigmoid

TEST:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 16

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

LOGS:
  DIR: logs/Charades/I3D_32x4_R50_K400/

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
