_BASE_: SLOWFAST_PROG_76x8_R50_K400.yaml

TRAIN:
  CHECKPOINT_FILE_PATH: obs://bucket-5006/data/slowfast/models/k400/SLOWFAST_8x8_R50.pkl

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Charades/
  PATH_PREFIX: obs://bucket-5006/data/Charades/Charades_v1_rgb

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: True

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Charades/MOX_SLOWFAST_PROG_76x8_R50_K400

NUM_GPUS: 8
