_BASE_: SLOWFAST_16x8_R101_K600.yaml

TRAIN:
  BATCH_SIZE: 32
  CHECKPOINT_FILE_PATH: obs://bucket-5006/data/slowfast/models/k600/SLOWFAST_16x8_R101.pkl

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Charades/
  PATH_PREFIX: obs://bucket-5006/data/Charades/Charades_v1_rgb

SOLVER:
  BASE_LR: 0.075
  WARMUP_START_LR: 0.0002

TEST:
  BATCH_SIZE: 32

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Charades/MOX_SLOWFAST_16x8_R101_K600

NUM_GPUS: 8
