_BASE_: SLOWFAST_PROG_76x8_R101_K400.yaml

TRAIN:
  CHECKPOINT_FILE_PATH: obs://bucket-5006/penggao/logs/progress-action/Kinetics/MOX2_SLOWFAST_8x8_R101.77.22/checkpoints/checkpoint_epoch_00196.pyth

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Charades/
  PATH_PREFIX: obs://bucket-5006/data/Charades/Charades_v1_rgb

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Charades/MOX_SLOWFAST_PROG_76x8_R101_K400

NUM_GPUS: 8
