_BASE_: SLOW_PROG_36x8_R50_K400.yaml

TRAIN:
  BATCH_SIZE: 32
  CHECKPOINT_FILE_PATH: obs://bucket-5006/penggao/logs/progress-action/Charades/MOX_SLOW_PROG_36x8_R50_K400_tb_momentum.35.52/checkpoints/checkpoint_epoch_00010.pyth
  CHECKPOINT_TYPE: pytorch
  TRANSFER_WEIGHT: False

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Charades/
  PATH_PREFIX: obs://bucket-5006/data/Charades/Charades_v1_rgb

PGT:
  ENABLE: True
  CACHE: last
  CACHE_MOMENTUM: 0.1
  TRUNCATE_GRAD: True

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

TEST:
  BATCH_SIZE: 4

SOLVER:
  STEPS: [0, 20]

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Charades/MOX_SLOW_PROG_36x8_R50_K400_tb_momentum

NUM_GPUS: 4