_BASE_: SLOWFAST_PROG_76x8_R101_K600.yaml

TRAIN:
  CHECKPOINT_TYPE: aia
  CHECKPOINT_FILE_PATH: obs://bucket-5006/data/slowfast/models/k600/SLOWFAST_8x8_R101.pth

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/Charades/
  PATH_PREFIX: obs://bucket-5006/data/Charades/Charades_v1_rgb

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: True

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/Charades/MOX_SLOWFAST_PROG_76x8_R101_K600

NUM_GPUS: 8
