_BASE_: SLOW_PROG_76x8_R50_K400.yaml

PGT:
  MGRID: True
  MGRID_LRSCALES: [1, 1, 1, 1]
  MGRID_STEPS: [5, 6, 7, 8]
  MGRID_STEP_LEN: [[16], [14], [12], [11]]

SOLVER:
  BASE_LR: 0.025
  STEPS: [0, 20]
  MAX_EPOCH: 20
  WARMUP_EPOCHS: 1.0

TEST:
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOW_PROG_76x8_R50_K400_mgrid/

NUM_GPUS: 4
