_BASE_: SLOW_8x8_R50_K400.yaml

DATA:
  NUM_FRAMES: 15

PGT:
  ENABLE: True
  STEP_LEN: 8
  PG_EVAL: True
  ENSEMBLE_METHOD: max

SOLVER:
  STEPS: [0, 10, 20]
  MAX_EPOCH: 30

TEST:
  BATCH_SIZE: 2
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOW_PROG_15x8_R50_K400/

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
