_BASE_: SLOW_8x8_R50_K400.yaml

NONLOCAL:
  LOCATION: [[[]], [[1, 3]], [[1, 3, 5]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
  USE_BN: False

LOGS:
  DIR: logs/Chardes/SLOW_NLN_8x8_R50_K400