_BASE_: SLOW_8x8_R50_K400.yaml

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: 8

SOLVER:
  STEPS: [0, 6, 12]
  MAX_EPOCH: 20
  WARMUP_EPOCHS: 1.0

MODEL:
  FINAL_POOL: ["avg", "max"]

TEST:
  BATCH_SIZE: 2
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOW_PROG_36x8_R50_K400/

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
