_BASE_: SLOW_8x8_R50_K400.yaml

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: 8
  STEPS: 5
  OVERLAP: 1
  PG_EVAL: True
  TRAIN_TOGETHER: True
  ENSEMBLE_METHOD: max

SOLVER:
  BASE_LR: 0.025
  STEPS: [0, 10, 16]
  MAX_EPOCH: 20
  WARMUP_EPOCHS: 1.0

TEST:
  BATCH_SIZE: 2
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOW_PROG_36x8_R50_K400/

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
