_BASE_: SLOW_16x8_R101_K400.yaml

TRAIN:
  BATCH_SIZE: 32

DATA:
  NUM_FRAMES: 76

PGT:
  ENABLE: True
  STEP_LEN: [16]
  STEPS: 5
  OVERLAP: [1]
  CACHE: max
  CACHE_MOMENTUM: 0.25
  PG_EVAL: True
  TRAIN_TOGETHER: True
  ENSEMBLE_METHOD: max

SOLVER:
  BASE_LR: 0.025
  STEPS: [0, 20]
  MAX_EPOCH: 20
  WARMUP_EPOCHS: 1.0

TEST:
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOW_PROG_76x8_R101_K400/

NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
