_BASE_: SLOW_8x8_R50_K400.yaml

TRAIN:
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_FILE_PATH: /home/pg/data/models/k400/SLOW_NLN_8x8_R50.pkl

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: 8
  PG_EVAL: True
  ENSEMBLE_METHOD: max

NONLOCAL:
  LOCATION: [[[]], [[1, 3]], [[1, 3, 5]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
  PROGRESS: True

SOLVER:
  STEPS: [0, 10, 15]
  MAX_EPOCH: 20
  WARMUP_EPOCHS: 1.0

TEST:
  BATCH_SIZE: 4
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOW_PROGNLN_36x8_R50_K400

NUM_GPUS: 4