_BASE_: SLOWFAST_16x8_R50_K400.yaml

DATA:
  NUM_FRAMES: 304

PGT:
  ENABLE: True
  STEP_LEN: [16, 64]
  STEPS: 5
  OVERLAP: [1, 1]
  CACHE: max
  CACHE_MOMENTUM: 0.25
  PG_EVAL: True
  TRAIN_TOGETHER: True
  ENSEMBLE_METHOD: max

SOLVER:
  BASE_LR: 0.0125
  STEPS: [0, 20]
  MAX_EPOCH: 25
  WARMUP_EPOCHS: 4.0

TEST:
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOWFAST_PROG_76x8_R50_K400/