_BASE_: SLOW_PROG_36x8_R50_K400.yaml

PGT:
  MGRID: True
  MGRID_LRSCALES: [1, 0.5, 0.5, 0.33]
  MGRID_STEPS: [5, 6, 7, 9]
  MGRID_STEP_LEN: [8, 7, 6, 5]

SOLVER:
  BASE_LR: 0.025
  STEPS: [0, 20]
  MAX_EPOCH: 20
  WARMUP_EPOCHS: 1.0

TEST:
  BATCH_SIZE: 2
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/Charades/SLOW_PROG_36x8_R50_K400_mgrid/

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
