TRAIN:
  DATASET: charades
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  FULL_TIME_EVAL: True
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_FILE_PATH: /home/pg/data/models/k400/X3D_M.pyth

X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12

TEST:
  ENABLE: True
  DATASET: charades
  BATCH_SIZE: 32
  NUM_SPATIAL_CROPS: 3
  NUM_ENSEMBLE_VIEWS: 10

DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  MULTI_LABEL: True
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: /home/pg/data/Charades/
  PATH_PREFIX: /home/pg/data/Charades/Charades_v1_rgb

RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False

BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: frozen_batchnorm

SOLVER:
  BASE_LR: 0.05
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 20, 30]
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  WARMUP_EPOCHS: 4.0
  WARMUP_START_LR: 0.0002
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 157
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: bce_logit
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5
  FINAL_POOL: ["avg", "max"]

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

LOGS:
  DIR: logs/Charades/X3D_M_K400
  LOG_MODEL: False

NUM_GPUS: 2
RNG_SEED: 0
