_BASE_: SLOWFAST_8x8_R50.yaml

TRAIN:
  BATCH_SIZE: 128
  EVAL_PERIOD: 10

DATA:
  PATH_TO_DATA_DIR: obs://video-understanding-shanghai/penggao/data/miniKinetics/
  PATH_PREFIX: obs://video-understanding-shanghai/poli/datasets/Kinetics/

SOLVER:
  BASE_LR: 0.4
  WARMUP_START_LR: 0.04

TEST:
  BATCH_SIZE: 128

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://video-understanding-shanghai/penggao/logs/progress-action/miniKinetics/MOX2_SLOWFAST_8x8_R50

NUM_SHARDS: 2