_BASE_: MOX_SLOW_PROG_36x8_R50_mgrid.yaml

SOLVER:
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001]
  STEPS: [0, 47, 77, 98]
  MAX_EPOCH: 120
  WARMUP_EPOCHS: 17.0

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/miniKinetics/MOX_SLOW_PROG_36x8_R50_mgrid_stepwise