_BASE_: SLOWFAST_PROG_36x8_R50.yaml

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/miniKinetics/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

SOLVER:
  BASE_LR: 0.2
  WARMUP_START_LR: 0.02

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/miniKinetics/MOX_SLOWFAST_PROG_36x8_R50

NUM_SHARDS: 2