_BASE_: SLOW_PROG_36x8_R50.yaml

TRAIN:
  BATCH_SIZE: 128
  EVAL_PERIOD: 1

DATA:
  PATH_TO_DATA_DIR: obs://bucket-5006/data/miniKinetics/
  PATH_PREFIX: obs://bucket-5006/data/Kinetics_400/rgb/

SOLVER:
  BASE_LR: 0.8
  WARMUP_START_LR: 0.08

TEST:
  BATCH_SIZE: 32

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://bucket-5006/penggao/logs/progress-action/miniKinetics/MOX_SLOW_PROG_36x8_R50_2xlr

NUM_SHARDS: 2