TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 256
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True

DATA:
  NUM_FRAMES: 36
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data/mini-kinetics
  PATH_PREFIX: /home/pg/data/Kinetics_400

BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.00

PGT:
  ENABLE: True
  TRAIN_TOGETHER: False
  STEP_LEN: 8

SOLVER:
  BASE_LR: 0.4
  LR_POLICY: cosine
  MAX_EPOCH: 98
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 17.0
  WARMUP_START_LR: 0.04
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 200
  ARCH: regnet3d
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 3

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: False

LOGS:
  DIR: logs/miniKinetics/REGNET3D_PROG_36x8_400M/

NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0


