TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 48
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True

DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data/mini-kinetics
  PATH_PREFIX: data/mini-kinetics

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 16
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]

NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.075
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 44, 88, 118]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 200
  ARCH: r3d
  MODEL_NAME: RegNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 48

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

LOGS:
  DIR: logs/miniKinetics/R3D_8x8_400M/

NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
