_BASE_: SLOW_PROG_36x8_R50.yaml

PGT:
  MGRID: True
  MGRID_LRSCALES: [1, 0.5, 0.3, 0.25]
  MGRID_STEPS: [5, 6, 7, 9]
  MGRID_STEP_LEN: [8, 7, 6, 5]

TEST:
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/miniKinetics/SLOW_PROG_36x8_R50_mgrid/
