TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 256
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True

DATA:
  NUM_FRAMES: 36
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/pg/data/miniKinetics
  PATH_PREFIX: /home/pg/data/Kinetics_400

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]

NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product

BN:
  USE_PRECISE_STATS: False

PGT:
  ENABLE: True
  TRAIN_TOGETHER: False
  STEP_LEN: 8

SOLVER:
  BASE_LR: 0.4
  LR_POLICY: cosine
  MAX_EPOCH: 98
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 17.0
  WARMUP_START_LR: 0.04
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 200
  ARCH: slow
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 3

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

LOGS:
  DIR: logs/miniKinetics/SLOW_PROG_36x8_R50/

NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0