_BASE_: SLOW_8x8_R50.yaml

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: [8]
  STEPS: 5
  OVERLAP: [1]
  CACHE: last
  CACHE_MOMENTUM: 0.25
  TRAIN_TOGETHER: True
  PG_EVAL: False
  TPOOL_SIZE: [4]

SOLVER:
  MAX_EPOCH: 98
  WARMUP_EPOCHS: 17.0

TEST:
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3
  CYCLIC_LOAD: True

LOGS:
  DIR: logs/miniKinetics/SLOW_PROG_36x8_R50