_BASE_: SLOW_8x8_R50.yaml

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: 8
  STEPS: 5
  OVERLAP: 1
  PG_EVAL: True

SOLVER:
  MAX_EPOCH: 98
  WARMUP_EPOCHS: 17.0

TEST:
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 3
  NUM_SPATIAL_CROPS: 3

LOGS:
  DIR: logs/miniKinetics/SLOW_PROG_36x8_R50