TRAIN:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_FILE_PATH: /home/pg/data/models/k400/SLOW_8x8_R50.pkl

DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: /home/pg/data/SSv2/
  PATH_PREFIX: /home/pg/data/SSv2/20bn-something-something-v2

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]

NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]

BN:
  USE_PRECISE_STATS: False
  WEIGHT_DECAY: 0.0
  NORM_TYPE: frozen_batchnorm

SOLVER:
  BASE_LR: 2.5e-3
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 14, 18]
  MAX_EPOCH: 22
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 174
  ARCH: slow
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

LOGS:
  DIR: logs/SSv2/SLOW_8x8_R50_K400/

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
