_BASE_: SLOW_PROG_36x8_R50_K400.yaml

TRAIN:
  BATCH_SIZE: 128
  CHECKPOINT_FILE_PATH: obs://bucket-5006/data/slowfast/models/k400/SLOW_8x8_R101.pyth
  CHECKPOINT_TYPE: pytorch

AVA:
  FRAME_DIR: obs://bucket-5006/data/AVA/fair/frames
  FRAME_LIST_DIR: obs://bucket-5006/data/AVA/fair/frame_lists
  ANNOTATION_DIR: obs://bucket-5006/data/AVA/fair/annotations

TEST:
  BATCH_SIZE: 8

DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: False

LOGS:
  DIR: obs://bucket-5006/lyz/logs/progress-action/AVA/MOX_SLOW_PROG_36x8_R101_K400

NUM_GPUS: 8
NUM_SHARDS: 1