TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /home/pg/data/models/k400/SLOWFAST_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2

DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  # TODO: test crop size 224 or 256?
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]

DETECTION:
  ENABLE: True

AVA:
  DETECTION_SCORE_THRESH: 0.8

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]

NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]

BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.05
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15, 20]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.0000625
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 80
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid

TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 4

DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True

LOGS:
  DIR: logs/AVA/SLOWFAST_8x8_R50_K400.yaml

NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0