_BASE_: SLOW_8x8_R50_K400.yaml

TRAIN:
  BATCH_SIZE: 32
  EVAL_PERIOD: 1

TEST:
  BATCH_SIZE: 8

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: [8]
  STEPS: 5
  OVERLAP: [1]
  CACHE: last
  CACHE_MOMENTUM: 0.1
  PG_EVAL: True
  TRAIN_TOGETHER: False
  ENSEMBLE_METHOD: max
  TPOOL_SIZE: [1]

SOLVER:
  BASE_LR: 0.04
  STEPS: [0, 3, 4, 5]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 5
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.0000625

LOGS:
  DIR: logs/AVA/SLOW_PROG_36x8_R50_K400

NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0

