_BASE_: SLOW_8x8_R50_K400.yaml

TRAIN:
  BATCH_SIZE: 32
  EVAL_PERIOD: 1

DATA:
  NUM_FRAMES: 36

PGT:
  ENABLE: True
  STEP_LEN: 8

SOLVER:
  BASE_LR: 0.05
  STEPS: [0, 5, 7, 10]
  MAX_EPOCH: 10
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.0000625

LOGS:
  DIR: logs/AVA/SLOW_PROG_36x8_R50_K400

NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0

